/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JuegoNuevo.java
 *
 * Created on 22-ene-2010, 17:36:38
 */

package jugador.InterfazGrafica;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import jugador.Comunicacion;

/**
 *
 * @author Nelly
 */
public class JuegoNuevo extends javax.swing.JFrame {

    /** Creates new form JuegoNuevo */
    public JuegoNuevo() {
        initComponents();
        inicializarComponentesPropios();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPFPasswordJugador2 = new javax.swing.JPasswordField();
        jPFPasswordJugador1 = new javax.swing.JPasswordField();
        jCBListaNickJugador2 = new javax.swing.JComboBox();
        jCBListaNickJugador1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jBAtras = new javax.swing.JButton();
        jLpassword1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLnick1 = new javax.swing.JLabel();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(923, 669));
        setName("Form"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(jugador.InterfazGrafica.ProyectoiBattleApp.class).getContext().getResourceMap(JuegoNuevo.class);
        jPFPasswordJugador2.setText(resourceMap.getString("jPFPasswordJugador2.text")); // NOI18N
        jPFPasswordJugador2.setName("jPFPasswordJugador2"); // NOI18N
        getContentPane().add(jPFPasswordJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 280, 110, -1));

        jPFPasswordJugador1.setText(resourceMap.getString("jPFPasswordJugador1.text")); // NOI18N
        jPFPasswordJugador1.setName("jPFPasswordJugador1"); // NOI18N
        getContentPane().add(jPFPasswordJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 120, -1));

        jCBListaNickJugador2.setName("jCBListaNickJugador2"); // NOI18N
        getContentPane().add(jCBListaNickJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 230, 110, -1));

        jCBListaNickJugador1.setName("jCBListaNickJugador1"); // NOI18N
        getContentPane().add(jCBListaNickJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 120, -1));

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1jBContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 450, 90, 30));

        jBAtras.setText(resourceMap.getString("jBAtras.text")); // NOI18N
        jBAtras.setName("jBAtras"); // NOI18N
        jBAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jBAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 70, 30));

        jLpassword1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLpassword1.setForeground(resourceMap.getColor("jLnick1.foreground")); // NOI18N
        jLpassword1.setText(resourceMap.getString("jLpassword1.text")); // NOI18N
        jLpassword1.setName("jLpassword1"); // NOI18N
        getContentPane().add(jLpassword1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 140, 20));

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLnick1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 140, 20));

        jLabel2.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel2.setForeground(resourceMap.getColor("jLnick1.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, 140, 20));

        jLabel3.setIcon(resourceMap.getIcon("jLabel3.icon")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, 110, 90));

        jLnick1.setFont(resourceMap.getFont("jLnick1.font")); // NOI18N
        jLnick1.setForeground(resourceMap.getColor("jLnick1.foreground")); // NOI18N
        jLnick1.setText(resourceMap.getString("jLnick1.text")); // NOI18N
        jLnick1.setName("jLnick1"); // NOI18N
        getContentPane().add(jLnick1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 140, 20));

        jLFondo.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLFondo.setIcon(resourceMap.getIcon("jLFondo.icon")); // NOI18N
        jLFondo.setText(resourceMap.getString("jLFondo.text")); // NOI18N
        jLFondo.setName("jLFondo"); // NOI18N
        getContentPane().add(jLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private  void inicializarComponentesPropios()
    {
        cargarListaEnBoton(1);
        cargarListaEnBoton(2);
    }

    private void cargarListaEnBoton(int a)
    {
        ArrayList <String> listaNickObtenida = new ArrayList();
        listaNickObtenida = Comunicacion.obtenerListaNick().getListaNick();
        if(a==1)
        {
            for(String nick: listaNickObtenida)
                jCBListaNickJugador1.addItem(nick);
        }
        else
        {
            for(String nick: listaNickObtenida)
                jCBListaNickJugador2.addItem(nick);
        }
    }


    private void jButton1jBContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1jBContinuarActionPerformed
        
        if ((jPFPasswordJugador1.getPassword().length==0) || (jPFPasswordJugador2.getPassword().length==0))
             JOptionPane.showMessageDialog(null,"Deben rellenar todos los campos para lograr crear una partida","Advertencia",2,null);
        else
        {
           String mensaje = Comunicacion.crearPartida(jCBListaNickJugador1, jPFPasswordJugador1.getPassword(),
                                          jCBListaNickJugador2, jPFPasswordJugador2.getPassword());
            if(mensaje.equals(""))
            {
                JOptionPane.showMessageDialog(null,"Se ha creado exitosamente la partida","iBattle",2,null);
//                PantallaColocarBarcos barcos = new PantallaColocarBarcos();
//                barcos.setVisible(true);
//                this.setVisible(false);





                this.setVisible(false);
                TableroPlayer1 tableroPlayer1 = new TableroPlayer1();
                tableroPlayer1.setLocationRelativeTo(null);
                tableroPlayer1.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null,mensaje,"Advertencia",1,null);
                jPFPasswordJugador1.setText(null);
                jPFPasswordJugador2.setText(null);
            }

        }
    }//GEN-LAST:event_jButton1jBContinuarActionPerformed

    private void jBAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBAtrasActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegoNuevo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtras;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCBListaNickJugador1;
    private javax.swing.JComboBox jCBListaNickJugador2;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLnick1;
    private javax.swing.JLabel jLpassword1;
    private javax.swing.JPasswordField jPFPasswordJugador1;
    private javax.swing.JPasswordField jPFPasswordJugador2;
    // End of variables declaration//GEN-END:variables

}
