/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaCarga.java
 *
 * Created on 22-ene-2010, 17:37:35
 */

package jugador.InterfazGrafica;

import java.util.ArrayList;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import jugador.Comunicacion;

/**
 *
 * @author Nelly
 */
public class PantallaCarga extends javax.swing.JFrame {

    /** Creates new form PantallaCarga */
    public PantallaCarga() {
        initComponents();
        inicializarComponentesPropios();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPFPasswordJugador1 = new javax.swing.JPasswordField();
        jPFPasswordJugador2 = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jCBListaNickJugador1 = new javax.swing.JComboBox();
        jCBListaNickJugador2 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jBContinuar = new javax.swing.JButton();
        jBAtras = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(923, 669));
        setName("Form"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 270, 110, 20));

        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(211, 120, -1, -1));

        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 140, -1, -1));

        jLabel4.setName("jLabel4"); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 110, -1, -1));

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(jugador.InterfazGrafica.ProyectoiBattleApp.class).getContext().getResourceMap(PantallaCarga.class);
        jPFPasswordJugador1.setText(resourceMap.getString("jPFPasswordJugador1.text")); // NOI18N
        jPFPasswordJugador1.setName("jPFPasswordJugador1"); // NOI18N
        getContentPane().add(jPFPasswordJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 130, -1));

        jPFPasswordJugador2.setText(resourceMap.getString("jPFPasswordJugador2.text")); // NOI18N
        jPFPasswordJugador2.setName("jPFPasswordJugador2"); // NOI18N
        getContentPane().add(jPFPasswordJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 120, -1));

        jLabel5.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel5.setForeground(resourceMap.getColor("jLabel5.foreground")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        jCBListaNickJugador1.setName("jCBListaNickJugador1"); // NOI18N
        getContentPane().add(jCBListaNickJugador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 220, 130, -1));

        jCBListaNickJugador2.setName("jCBListaNickJugador2"); // NOI18N
        getContentPane().add(jCBListaNickJugador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 120, -1));

        jLabel6.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel6.setForeground(resourceMap.getColor("jLabel8.foreground")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        jLabel10.setIcon(resourceMap.getIcon("jLabel10.icon")); // NOI18N
        jLabel10.setName("jLabel10"); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 580, 110, 90));

        jLabel7.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel7.setForeground(resourceMap.getColor("jLabel8.foreground")); // NOI18N
        jLabel7.setText(resourceMap.getString("jLabel7.text")); // NOI18N
        jLabel7.setName("jLabel7"); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(474, 270, 140, -1));

        jLabel8.setFont(resourceMap.getFont("jLabel5.font")); // NOI18N
        jLabel8.setForeground(resourceMap.getColor("jLabel8.foreground")); // NOI18N
        jLabel8.setText(resourceMap.getString("jLabel8.text")); // NOI18N
        jLabel8.setName("jLabel8"); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, 150, -1));

        jBContinuar.setText(resourceMap.getString("jBContinuar.text")); // NOI18N
        jBContinuar.setName("jBContinuar"); // NOI18N
        jBContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBContinuarActionPerformed(evt);
            }
        });
        getContentPane().add(jBContinuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 350, -1, -1));

        jBAtras.setText(resourceMap.getString("jBAtras.text")); // NOI18N
        jBAtras.setName("jBAtras"); // NOI18N
        jBAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jBAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 350, -1, -1));

        jLabel9.setIcon(resourceMap.getIcon("jLabel9.icon")); // NOI18N
        jLabel9.setText(resourceMap.getString("jLabel9.text")); // NOI18N
        jLabel9.setName("jLabel9"); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private  void inicializarComponentesPropios()
    {
        cargarListaEnBoton();
    }

    private void cargarListaEnBoton()
    {
        ArrayList <String> listaNick = new ArrayList();
        listaNick = Comunicacion.obtenerListaNick().getListaNick();
            for(String nick: listaNick)
                jCBListaNickJugador1.addItem(nick);

            for(String nick: listaNick)
                jCBListaNickJugador2.addItem(nick);

    }

    private void jBContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBContinuarActionPerformed

        if ((jPFPasswordJugador1.getPassword().length==0) || (jPFPasswordJugador2.getPassword().length==0))
             JOptionPane.showMessageDialog(null,"Deben rellenar todos los campos para lograr cargar una partida","Advertencia",2,null);
        else
        {
           String mensaje = Comunicacion.cargarPartida(jCBListaNickJugador1, jPFPasswordJugador1.getPassword(),
                                          jCBListaNickJugador2, jPFPasswordJugador2.getPassword());
            if(mensaje.equals(""))
            {
                JOptionPane.showMessageDialog(null,"Se cargo Exitósamente la partida","iBattle",2,null);
                this.setVisible(false);
                PantallaJuego pantallaJuego = new PantallaJuego();
                this.setVisible(false);
                pantallaJuego.setLocationRelativeTo(null);
                pantallaJuego.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(null,mensaje,"Advertencia",1,null);
                jPFPasswordJugador1.setText(null);
                jPFPasswordJugador2.setText(null);
            }
            
        }
    }//GEN-LAST:event_jBContinuarActionPerformed

    private void jBAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBAtrasActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaCarga().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtras;
    private javax.swing.JButton jBContinuar;
    private javax.swing.JComboBox jCBListaNickJugador1;
    private javax.swing.JComboBox jCBListaNickJugador2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPasswordField jPFPasswordJugador1;
    private javax.swing.JPasswordField jPFPasswordJugador2;
    // End of variables declaration//GEN-END:variables

}
