/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaRegistro.java
 *
 * Created on 22-ene-2010, 17:23:50
 */

package jugador.InterfazGrafica;

import javax.swing.JOptionPane;
import jugador.Comunicacion;

/**
 *
 * @author Nelly
 */
public class PantallaRegistro extends javax.swing.JFrame {
    public static String avatar;
    /** Creates new form PantallaRegistro */
    public PantallaRegistro() {
        initComponents();
        inicializarComponentesPropios();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLnombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLnombre1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTFNombre = new javax.swing.JTextField();
        jTFApellido = new javax.swing.JTextField();
        jTFNick = new javax.swing.JTextField();
        jPFPassword = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jTFDiaFecha = new javax.swing.JTextField();
        jTFMesFecha = new javax.swing.JTextField();
        jTFAñoFecha = new javax.swing.JTextField();
        jLfecha = new javax.swing.JLabel();
        jLfecha1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLListaImagenes = new javax.swing.JList();
        jBAvatar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jBAtras = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(923, 669));
        setName("Form"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(jugador.InterfazGrafica.ProyectoiBattleApp.class).getContext().getResourceMap(PantallaRegistro.class);
        jLnombre.setBackground(resourceMap.getColor("jLFondo.background")); // NOI18N
        jLnombre.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLnombre.setForeground(resourceMap.getColor("jLnombre.foreground")); // NOI18N
        jLnombre.setText(resourceMap.getString("jLnombre.text")); // NOI18N
        jLnombre.setName("jLnombre"); // NOI18N
        getContentPane().add(jLnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 64, -1));

        jLabel2.setBackground(resourceMap.getColor("jLFondo.background")); // NOI18N
        jLabel2.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel2.setForeground(resourceMap.getColor("jLnombre.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, -1, -1));

        jLabel3.setBackground(resourceMap.getColor("jLFondo.background")); // NOI18N
        jLabel3.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel3.setForeground(resourceMap.getColor("jLnombre.foreground")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, -1, -1));

        jLabel4.setBackground(resourceMap.getColor("jLFondo.background")); // NOI18N
        jLabel4.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel4.setForeground(resourceMap.getColor("jLnombre.foreground")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        jLnombre1.setBackground(resourceMap.getColor("jLFondo.background")); // NOI18N
        jLnombre1.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLnombre1.setForeground(resourceMap.getColor("jLnombre.foreground")); // NOI18N
        jLnombre1.setText(resourceMap.getString("jLnombre1.text")); // NOI18N
        jLnombre1.setName("jLnombre1"); // NOI18N
        getContentPane().add(jLnombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, 29));

        jLabel5.setBackground(resourceMap.getColor("jLFondo.background")); // NOI18N
        jLabel5.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel5.setForeground(resourceMap.getColor("jLnombre.foreground")); // NOI18N
        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 150, 20));

        jTFNombre.setName("jTFNombre"); // NOI18N
        jTFNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTFNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 170, -1));

        jTFApellido.setName("jTFApellido"); // NOI18N
        jTFApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFApellidoActionPerformed(evt);
            }
        });
        getContentPane().add(jTFApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 170, -1));

        jTFNick.setName("jTFNick"); // NOI18N
        jTFNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFNickActionPerformed(evt);
            }
        });
        getContentPane().add(jTFNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 180, 170, -1));

        jPFPassword.setName("jPFPassword"); // NOI18N
        getContentPane().add(jPFPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 170, 21));

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1jBContinuar(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 510, 99, 34));

        jTFDiaFecha.setText(resourceMap.getString("jTFDiaFecha.text")); // NOI18N
        jTFDiaFecha.setName("jTFDiaFecha"); // NOI18N
        jTFDiaFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFDiaFechaKeyReleased(evt);
            }
        });
        getContentPane().add(jTFDiaFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 31, -1));

        jTFMesFecha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTFMesFecha.setText(resourceMap.getString("jTFMesFecha.text")); // NOI18N
        jTFMesFecha.setName("jTFMesFecha"); // NOI18N
        jTFMesFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFMesFechaActionPerformed(evt);
            }
        });
        jTFMesFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFMesFechaKeyReleased(evt);
            }
        });
        getContentPane().add(jTFMesFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, 31, -1));

        jTFAñoFecha.setText(resourceMap.getString("jTFAñoFecha.text")); // NOI18N
        jTFAñoFecha.setName("jTFAñoFecha"); // NOI18N
        jTFAñoFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFAñoFechaActionPerformed(evt);
            }
        });
        jTFAñoFecha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFAñoFechaKeyReleased(evt);
            }
        });
        getContentPane().add(jTFAñoFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 41, -1));

        jLfecha.setText(resourceMap.getString("jLfecha.text")); // NOI18N
        jLfecha.setName("jLfecha"); // NOI18N
        getContentPane().add(jLfecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 130, -1, -1));

        jLfecha1.setText(resourceMap.getString("jLfecha1.text")); // NOI18N
        jLfecha1.setName("jLfecha1"); // NOI18N
        getContentPane().add(jLfecha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 18, -1));

        jScrollPane1.setName("jScrollPane1"); // NOI18N

        jLListaImagenes.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Bart Simpson", "Capitan", "Capitana", "Capitan Jack Sparrow", "Catalejo", "Davy Jones", "Elizabeth", "Piratas del Caribe", "Popeye", "South park", "South park 1", "Velero", "Yoda Star Wars" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jLListaImagenes.setName("jLListaImagenes"); // NOI18N
        jLListaImagenes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLListaImagenesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jLListaImagenes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 167, -1));

        jBAvatar.setName("jBAvatar"); // NOI18N
        getContentPane().add(jBAvatar, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 79, 81));

        jLabel6.setBackground(resourceMap.getColor("jLFondo.background")); // NOI18N
        jLabel6.setFont(resourceMap.getFont("jLabel6.font")); // NOI18N
        jLabel6.setForeground(resourceMap.getColor("jLabel6.foreground")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 60, -1));

        jBAtras.setText(resourceMap.getString("jBAtras.text")); // NOI18N
        jBAtras.setName("jBAtras"); // NOI18N
        jBAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jBAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 510, 90, 30));

        jSeparator1.setName("jSeparator1"); // NOI18N
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 460, -1));

        jSeparator2.setName("jSeparator2"); // NOI18N
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, 460, 20));

        jTextField2.setText(resourceMap.getString("jTextField2.text")); // NOI18N
        jTextField2.setName("jTextField2"); // NOI18N
        getContentPane().add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 150, -1));

        jTextField1.setForeground(resourceMap.getColor("jTextField1.foreground")); // NOI18N
        jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
        jTextField1.setName("jTextField1"); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 300, 50, 20));

        jLabel1.setIcon(resourceMap.getIcon("jLabel1.icon")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 570, 110, 90));

        jLFondo.setBackground(resourceMap.getColor("jLFondo.background")); // NOI18N
        jLFondo.setForeground(resourceMap.getColor("jLnombre.foreground")); // NOI18N
        jLFondo.setIcon(resourceMap.getIcon("jLFondo.icon")); // NOI18N
        jLFondo.setText(resourceMap.getString("jLFondo.text")); // NOI18N
        jLFondo.setName("jLFondo"); // NOI18N
        getContentPane().add(jLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inicializarComponentesPropios()
    {
       jBAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jugador/InterfazGrafica/img/DavyJones.png")));
                avatar="/jugador/InterfazGrafica/img/DavyJones.png";
    }

    private void jTFNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNombreActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTFNombreActionPerformed

    private void jTFApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFApellidoActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTFApellidoActionPerformed

    private void jTFNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFNickActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTFNickActionPerformed

    private void jButton1jBContinuar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1jBContinuar
        // el codigo viene aca
        if(jTFNombre.getText().isEmpty() || jTFApellido.getText().isEmpty() || jTFNick.getText().isEmpty()
                || jPFPassword.getPassword().length == 0) {
            JOptionPane.showMessageDialog(null,"Rellene todos los campos antes de Registrar el Usuario","Advertencia",2,null);
        } else {
            boolean exito =Comunicacion.crearNuevaPersona(jTFNombre.getText(), jTFApellido.getText(),
                            jTFNick.getText(), jPFPassword.getPassword(), avatar, jTFDiaFecha.getText(),
                            jTFMesFecha.getText(), jTFAñoFecha.getText());
            if (exito) {
                this.dispose();
                JOptionPane.showMessageDialog(null,"Nombre: "+ jTFNombre.getText() +"\n"+
                        "Apellido: "+ jTFApellido.getText() +"\n"+
                        "Fecha Nacimiento: " + jTFDiaFecha.getText() + "/" + jTFMesFecha.getText() +"/" +
                        jTFAñoFecha.getText() + "\n" + "Nick: "+ jTFNick.getText() +"\n" +
                        "Ha sido registrado Exitósamente!","iBattle",1,null);
            } else {
                jTFNick.setText(null);
                JOptionPane.showMessageDialog(null,"El nick ingresado ya existe, por favor ingrese otro","Advertencia",2,null);
            }
        }
}//GEN-LAST:event_jButton1jBContinuar

    private void jTFDiaFechaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFDiaFechaKeyReleased
        try {
            int año=Integer.parseInt(jTFDiaFecha.getText().trim());
            if(año>2009 || año<1)
                jTFDiaFecha.setText(null);
        } catch (NumberFormatException e) {
            jTFDiaFecha.setText(null);
        }
}//GEN-LAST:event_jTFDiaFechaKeyReleased

    private void jTFMesFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFMesFechaActionPerformed

    }//GEN-LAST:event_jTFMesFechaActionPerformed

    private void jTFMesFechaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFMesFechaKeyReleased
        try {
            int mes=Integer.parseInt(jTFMesFecha.getText().trim());
            if(mes>12 || mes<1)
                jTFMesFecha.setText(null);
        } catch (NumberFormatException e) {
            jTFMesFecha.setText(null);
        }
}//GEN-LAST:event_jTFMesFechaKeyReleased

    private void jTFAñoFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFAñoFechaActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jTFAñoFechaActionPerformed

    private void jTFAñoFechaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFAñoFechaKeyReleased
        try {
            int año=Integer.parseInt(jTFAñoFecha.getText().trim());
            if(año>2009 || año<1)
                jTFAñoFecha.setText(null);
        } catch (NumberFormatException e) {
            jTFAñoFecha.setText(null);
        }
}//GEN-LAST:event_jTFAñoFechaKeyReleased

    private void jLListaImagenesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLListaImagenesMouseClicked
        int opc = jLListaImagenes.getSelectedIndex();
        switch (opc) {
            case 0:
                jBAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jugador/InterfazGrafica/img/bart.png")));
                avatar="/jugador/InterfazGrafica/img/bart.png";
                break;
            case 1:
                jBAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jugador/InterfazGrafica/img/capitan.png")));
                avatar="/jugador/InterfazGrafica/img/capitan.png";
                break;
            case 2:
                jBAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jugador/InterfazGrafica/img/capitana.png")));
                avatar="/jugador/InterfazGrafica/img/capitana.png";
                break;
            case 3:
                jBAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jugador/InterfazGrafica/img/captain-jack-sparrow.png")));
                avatar="/jugador/InterfazGrafica/img/captain-jack-sparrow.png";
                break;
            case 4:
                jBAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jugador/InterfazGrafica/img/catalejo.png")));
                avatar="/jugador/InterfazGrafica/img/catalejo.png";
                break;
            case 5:
                jBAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jugador/InterfazGrafica/img/DavyJones.png")));
                avatar="/jugador/InterfazGrafica/img/DavyJones.png";
                break;
            case 6:
                jBAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jugador/InterfazGrafica/img/Elizabeth.png")));
                avatar="/jugador/InterfazGrafica/img/Elizabeth.png";
                break;
            case 7:
                jBAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jugador/InterfazGrafica/img/piratasdelcaribe.jpg")));
                avatar="/jugador/InterfazGrafica/img/piratasdelcaribe.jpg";
                break;
            case 8:
                jBAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jugador/InterfazGrafica/img/Popeye.png")));
                avatar="/jugador/InterfazGrafica/img/Popeye.png";
                break;
            case 9:
                jBAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jugador/InterfazGrafica/img/south-park.png")));
                avatar="/jugador/InterfazGrafica/img/south-park.png";
                break;
            case 10:
                jBAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jugador/InterfazGrafica/img/south-park1.png")));
                avatar="/jugador/InterfazGrafica/img/south-park1.png";
                break;
            case 11:
                jBAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jugador/InterfazGrafica/img/velero.png")));
                avatar="/jugador/InterfazGrafica/img/velero.png";
                break;
            case 12:
                jBAvatar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jugador/InterfazGrafica/img/yoda.png")));
                avatar="/jugador/InterfazGrafica/img/yoda.png";
                break;
        }
}//GEN-LAST:event_jLListaImagenesMouseClicked

    private void jBAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtrasActionPerformed

                this.dispose();
    }//GEN-LAST:event_jBAtrasActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaRegistro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtras;
    private javax.swing.JButton jBAvatar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JList jLListaImagenes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLfecha;
    private javax.swing.JLabel jLfecha1;
    private javax.swing.JLabel jLnombre;
    private javax.swing.JLabel jLnombre1;
    private javax.swing.JPasswordField jPFPassword;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTFApellido;
    private javax.swing.JTextField jTFAñoFecha;
    private javax.swing.JTextField jTFDiaFecha;
    private javax.swing.JTextField jTFMesFecha;
    private javax.swing.JTextField jTFNick;
    private javax.swing.JTextField jTFNombre;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}
