/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaEliminar.java
 *
 * Created on 22-ene-2010, 17:33:11
 */

package jugador.InterfazGrafica;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import jugador.Comunicacion;

/**
 *
 * @author Nelly
 */
public class PantallaEliminar extends javax.swing.JFrame {

    /** Creates new form PantallaEliminar */
    public PantallaEliminar() {
        initComponents();
        inicializarComponentesPropios();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPFPassword = new javax.swing.JPasswordField();
        jCBListaNick = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBAtras = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(923, 669));
        setName("Form"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(jugador.InterfazGrafica.ProyectoiBattleApp.class).getContext().getResourceMap(PantallaEliminar.class);
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1jBContinuar(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 490, -1, -1));

        jPFPassword.setName("jPFPassword"); // NOI18N
        jPFPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPFPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(jPFPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 310, 144, -1));

        jCBListaNick.setName("jCBListaNick"); // NOI18N
        jCBListaNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBListaNickActionPerformed(evt);
            }
        });
        getContentPane().add(jCBListaNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 144, -1));

        jLabel2.setFont(resourceMap.getFont("jLabel2.font")); // NOI18N
        jLabel2.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, -1, -1));

        jLabel1.setFont(resourceMap.getFont("jLabel1.font")); // NOI18N
        jLabel1.setForeground(resourceMap.getColor("jLabel1.foreground")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, 20));

        jLabel4.setIcon(resourceMap.getIcon("jLabel4.icon")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 580, 110, 90));

        jBAtras.setText(resourceMap.getString("jBAtras.text")); // NOI18N
        jBAtras.setName("jBAtras"); // NOI18N
        jBAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jBAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, -1, -1));

        jLabel3.setIcon(resourceMap.getIcon("jLabel3.icon")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private  void inicializarComponentesPropios()
    {
        int i;

        ArrayList <String> listaNickObtenida = Comunicacion.obtenerListaNick().getListaNick();
        for(String nick: listaNickObtenida)
        {
            jCBListaNick.addItem(nick);
        }

    }

    private void jButton1jBContinuar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1jBContinuar

        if (jPFPassword.getPassword().length==0)
             JOptionPane.showMessageDialog(null,"Debe rellenar todos los campos para lograr eliminar la cuenta","Advertencia",2,null);
        else
        {
            if(Comunicacion.eliminarPersona(jCBListaNick , jPFPassword.getPassword()))
            {
                JOptionPane.showMessageDialog(null,"Se elimino correctamente","iBattle",1,null);
                this.setVisible(false);
            }
            else
            {
                JOptionPane.showMessageDialog(null,"La combinacion nick/password es incorrecta","iBattle",2,null);
                jPFPassword.setText(null);
            }
        }
}//GEN-LAST:event_jButton1jBContinuar

    private void jPFPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPFPasswordActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_jPFPasswordActionPerformed

    private void jCBListaNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBListaNickActionPerformed
        
    }//GEN-LAST:event_jCBListaNickActionPerformed

    private void jBAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBAtrasActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaEliminar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtras;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jCBListaNick;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField jPFPassword;
    // End of variables declaration//GEN-END:variables

}
