/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaDecision.java
 *
 * Created on 22-ene-2010, 17:34:41
 */

package jugador.InterfazGrafica;


/**
 *
 * @author Nelly
 */
public class PantallaDecision extends javax.swing.JFrame {

    /** Creates new form PantallaDecision */
    public PantallaDecision() {
        initComponents();
    }


    

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jBCargarParitda = new javax.swing.JButton();
        jBAtras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(923, 669));
        setName("Form"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(jugador.InterfazGrafica.ProyectoiBattleApp.class).getContext().getResourceMap(PantallaDecision.class);
        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1jBJuevoNuevo(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 310, 166, 35));

        jBCargarParitda.setText(resourceMap.getString("jBCargarParitda.text")); // NOI18N
        jBCargarParitda.setName("jBCargarParitda"); // NOI18N
        jBCargarParitda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCargarParitdaActionPerformed(evt);
            }
        });
        getContentPane().add(jBCargarParitda, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, 166, 34));

        jBAtras.setText(resourceMap.getString("jBAtras.text")); // NOI18N
        jBAtras.setName("jBAtras"); // NOI18N
        jBAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(jBAtras, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 420, -1, -1));

        jLabel1.setIcon(resourceMap.getIcon("jLabel1.icon")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 580, 110, 90));

        jLFondo.setIcon(resourceMap.getIcon("jLFondo.icon")); // NOI18N
        jLFondo.setText(resourceMap.getString("jLFondo.text")); // NOI18N
        jLFondo.setName("jLFondo"); // NOI18N
        getContentPane().add(jLFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1jBJuevoNuevo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1jBJuevoNuevo
        // TODO add your handling code here:
        System.out.println("ENTRE A JUEVO NUEVO");
        JuegoNuevo juegoNuevo =  new JuegoNuevo();
        this.setVisible(false);
        juegoNuevo.setLocationRelativeTo(null);
        juegoNuevo.setVisible(true);
}//GEN-LAST:event_jButton1jBJuevoNuevo

    private void jBCargarParitdaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCargarParitdaActionPerformed
        PantallaCarga pantallaCarga = new PantallaCarga();
        pantallaCarga.setLocationRelativeTo(null);
        pantallaCarga.setVisible(true);
        this.setVisible(false);
}//GEN-LAST:event_jBCargarParitdaActionPerformed

    private void jBAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAtrasActionPerformed
        this.dispose();
    }//GEN-LAST:event_jBAtrasActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaDecision().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAtras;
    private javax.swing.JButton jBCargarParitda;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLFondo;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
