/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaColocarBarcos.java
 *
 * Created on 24/01/2010, 10:27:58 AM
 */

package jugador.InterfazGrafica;

import Interfaz.RegistroPartida;
import java.util.ArrayList;
import jugador.Comunicacion;

/**
 *
 * @author tony
 */
public class PantallaColocarBarcos extends javax.swing.JFrame {

    /** Creates new form PantallaColocarBarcos */
    public PantallaColocarBarcos() {
        initComponents();
        inicializarComponentesPropios();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCBListaRecord = new javax.swing.JComboBox();
        jCBListaPerdidas = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        jCBListaRecord.setName("jCBListaRecord"); // NOI18N
        jCBListaRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBListaRecordActionPerformed(evt);
            }
        });

        jCBListaPerdidas.setName("jCBListaPerdidas"); // NOI18N
        jCBListaPerdidas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBListaPerdidasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jCBListaPerdidas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCBListaRecord, javax.swing.GroupLayout.Alignment.LEADING, 0, 135, Short.MAX_VALUE))
                .addContainerGap(136, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jCBListaRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jCBListaPerdidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(123, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBListaRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBListaRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBListaRecordActionPerformed

    private void jCBListaPerdidasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBListaPerdidasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBListaPerdidasActionPerformed
    private void inicializarComponentesPropios()
    {

 




    }








    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaColocarBarcos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jCBListaPerdidas;
    private javax.swing.JComboBox jCBListaRecord;
    // End of variables declaration//GEN-END:variables

}
